services:
  nora:
    build: .
    container_name: nora
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./personas:/app/personas:ro
      - ./db.json:/app/db.json
# Need for my local deployment
#
#    networks:
#      - amiya
#
#networks:
#  amiya:
#    external: true
